stages:
  - testing
  - build      # part of second part of the tutorial
  - release    # part of third part of the tutorial

testsuite_image:
  stage: testing
  image: node:14
  script:
   - npm install
   - DATABASE_URL=mongodb://mongo:27017/test npm test
  services:
   - mongo:latest

   