stages:
  - testing
  - build
  - release

testsuite_image:
  stage: testing
  image: node:14
  script:
   - npm install
   - DATABASE_URL=mongodb://mongo:27017/test npm test
  services:
   - mongo:latest
